# setup-claude-mcp.ps1
# Sets up mcp-atlassian as a Claude Code MCP server for the current user.
# Run this script from anywhere — it uses its own location to find the repo.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File setup\setup-claude-mcp.ps1

$ErrorActionPreference = 'Stop'

# Resolve repo directory from script location
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoDir   = Split-Path -Parent $ScriptDir

$ConfigDir = Join-Path $env:APPDATA "mcp-atlassian"
$EnvFile   = Join-Path $ConfigDir ".env"

Write-Host "=== mcp-atlassian Claude Code Setup ===" -ForegroundColor Cyan
Write-Host "Repo: $RepoDir"
Write-Host ""

# --- Collect credentials ---

$JiraUrl = Read-Host "Jira URL [https://cyberport.atlassian.net]"
if (-not $JiraUrl) { $JiraUrl = "https://cyberport.atlassian.net" }
$JiraUrl = $JiraUrl.TrimEnd('/')

$JiraUsername = Read-Host "Jira username (your Atlassian email)"

Write-Host "Get your API token at: https://id.atlassian.com/manage-profile/security/api-tokens"
$JiraApiTokenSecure = Read-Host "Jira API token" -AsSecureString
$JiraApiToken = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
    [Runtime.InteropServices.Marshal]::SecureStringToBSTR($JiraApiTokenSecure)
)

$JiraProjectsFilter = Read-Host "Jira project filter (comma-separated, e.g. NOP) [NOP]"
if (-not $JiraProjectsFilter) { $JiraProjectsFilter = "NOP" }

# --- Create config directory ---

New-Item -ItemType Directory -Path $ConfigDir -Force | Out-Null

# --- Write .env ---

@"
# mcp-atlassian credentials
# Generated by setup-claude-mcp.ps1 — do not commit this file.

JIRA_URL=$JiraUrl
JIRA_USERNAME=$JiraUsername
JIRA_API_TOKEN=$JiraApiToken

# Restrict to specific projects (performance + safety)
JIRA_PROJECTS_FILTER=$JiraProjectsFilter

# Toolsets to load (default,jira_links,jira_agile covers core Jira without Confluence)
TOOLSETS=default,jira_links,jira_agile
"@ | Set-Content -Path $EnvFile -Encoding utf8

# Restrict read/write access to the current user only
icacls $EnvFile /inheritance:r /grant:r "${env:USERNAME}:(R,W)" | Out-Null
Write-Host "Credentials written to $EnvFile (restricted to current user)"

# --- Install Claude Code skills ---

$SkillsSrc = Join-Path $ScriptDir "skills"
$SkillsDst = Join-Path $env:USERPROFILE ".claude\commands"

if (Test-Path $SkillsSrc) {
    New-Item -ItemType Directory -Path $SkillsDst -Force | Out-Null
    Get-ChildItem -Path $SkillsSrc -Directory | ForEach-Object {
        $SkillFile = Join-Path $_.FullName "SKILL.md"
        if (Test-Path $SkillFile) {
            Copy-Item $SkillFile (Join-Path $SkillsDst "$($_.Name).md") -Force
            Write-Host "Installed skill: $($_.Name)"
        }
    }
}

# --- Register with Claude Code ---

Write-Host ""
if (Get-Command claude -ErrorAction SilentlyContinue) {
    # Remove existing registration if present, then re-add
    try { & claude mcp remove mcp-atlassian --scope user 2>$null } catch {}

    & claude mcp add mcp-atlassian `
        uv run --directory $RepoDir --env-file $EnvFile mcp-atlassian `
        --scope user

    Write-Host ""
    Write-Host "Verifying connection..."
    & claude mcp list
} else {
    Write-Host "Claude Code CLI not found in PATH."
    Write-Host "Register the server manually with:"
    Write-Host ""
    Write-Host "  claude mcp add mcp-atlassian uv run --directory `"$RepoDir`" --env-file `"$EnvFile`" mcp-atlassian --scope user"
}

Write-Host ""
Write-Host "Done. Restart Claude Code if it is currently running."
