#!/bin/bash
# setup-claude-mcp.sh
# Sets up mcp-atlassian as a Claude Code MCP server for the current user.
# Run this script from anywhere — it uses its own location to find the repo.

set -euo pipefail

# Resolve the repo directory from the script's own location
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

CONFIG_DIR="$HOME/.config/mcp-atlassian"
ENV_FILE="$CONFIG_DIR/.env"
RUN_SCRIPT="$CONFIG_DIR/run.sh"

echo "=== mcp-atlassian Claude Code Setup ==="
echo "Repo: $REPO_DIR"
echo

# --- Collect credentials ---

read -rp "Jira URL [https://cyberport.atlassian.net]: " JIRA_URL
JIRA_URL="${JIRA_URL:-https://cyberport.atlassian.net}"
JIRA_URL="${JIRA_URL%/}"  # strip trailing slash

read -rp "Jira username (your Atlassian email): " JIRA_USERNAME

echo "Get your API token at: https://id.atlassian.com/manage-profile/security/api-tokens"
read -rsp "Jira API token: " JIRA_API_TOKEN
echo

read -rp "Jira project filter (comma-separated, e.g. NOP) [NOP]: " JIRA_PROJECTS_FILTER
JIRA_PROJECTS_FILTER="${JIRA_PROJECTS_FILTER:-NOP}"

# --- Create config directory ---

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"

# --- Write .env ---

cat > "$ENV_FILE" <<EOF
# mcp-atlassian credentials
# Generated by setup-claude-mcp.sh — do not commit this file.

JIRA_URL=$JIRA_URL
JIRA_USERNAME=$JIRA_USERNAME
JIRA_API_TOKEN=$JIRA_API_TOKEN

# Restrict to specific projects (performance + safety)
JIRA_PROJECTS_FILTER=$JIRA_PROJECTS_FILTER

# Toolsets to load (default,jira_links,jira_agile covers core Jira without Confluence)
TOOLSETS=default,jira_links,jira_agile
EOF

chmod 600 "$ENV_FILE"
echo "Credentials written to $ENV_FILE (chmod 600)"

# --- Exclude from Time Machine ---

tmutil addexclusion "$CONFIG_DIR"
echo "Excluded $CONFIG_DIR from Time Machine backups"

# --- Write run.sh ---

cat > "$RUN_SCRIPT" <<EOF
#!/bin/bash
# Launched by Claude Code as the mcp-atlassian MCP server process.
set -a
source "$ENV_FILE"
set +a
exec uv run --directory "$REPO_DIR" mcp-atlassian
EOF

chmod +x "$RUN_SCRIPT"
echo "Launcher written to $RUN_SCRIPT"

# --- Install Claude Code skills ---

SKILLS_SRC="$SCRIPT_DIR/skills"
SKILLS_DST="$HOME/.claude/skills"

if [ -d "$SKILLS_SRC" ]; then
    for skill_dir in "$SKILLS_SRC"/*/; do
        skill_name="$(basename "$skill_dir")"
        mkdir -p "$SKILLS_DST/$skill_name"
        cp "$skill_dir/SKILL.md" "$SKILLS_DST/$skill_name/SKILL.md"
        echo "Installed skill: $skill_name"
    done
fi

# --- Register with Claude Code ---

echo
if command -v claude &>/dev/null; then
    # Remove existing registration if present, then re-add
    claude mcp remove mcp-atlassian --scope user 2>/dev/null || true
    claude mcp add mcp-atlassian /bin/bash "$RUN_SCRIPT" --scope user
    echo
    echo "Verifying connection..."
    claude mcp list
else
    echo "Claude Code CLI not found in PATH."
    echo "Register the server manually with:"
    echo "  claude mcp add mcp-atlassian /bin/bash \"$RUN_SCRIPT\" --scope user"
fi

echo
echo "Done. Restart Claude Code if it is currently running."
